// src/components/explore/SubTopicCard.tsx
'use client';
import React, { useEffect, useState } from 'react';
import item from "@/data/subTopics"

const YourComponent = () => {
  const [ratingCount, setRatingCount] = useState(0);
  const [imageSrc, setImageSrc] = useState('');

  return (
    <div className='w-max my-4'>
      <img
        src={item.cover}
        alt={item.cover}
        className='w-56 h-56 rounded-lg object-cover'
      />
      <h2 className='font-bold text-lg mt-4 overflow-ellipsis'>{item.title.length > 28
          ? item.title.slice(0, 28) + '...'
          : item.title}</h2>
      <p className='text-[#757575] mt-1'>
        {item.description.length > 28
          ? item.description.slice(0, 28) + '...'
          : item.description}
      </p>
      <p className='pl-3'>{ratingCount}</p>
    </div>
  );
};

export default YourComponent;

// src/components/explore/SubtopicCard.vue
<template>
  <div class="card">
    <!-- <img :src="cover" alt="Card Cover"> -->
    <h2 class="bold" style="font-size: 150%">{{ item.title }}</h2>
    <p>{{ item.description }}</p>
    <div class="flex">
      <div
        class="w-3 overflow-clip"
        v-if="
          item.feedback.aggregateRating >= 0.5 &&
          item.feedback.aggregateRating < 1
        "
      >
        <vue-feather
          v-if="item.feedback.aggregateRating >= 1"
          type="star"
        ></vue-feather>
      </div>
      <vue-feather
        v-if="item.feedback.aggregateRating >= 1"
        type="star"
      ></vue-feather>
      <div
        class="w-3 overflow-clip"
        v-if="
          item.feedback.aggregateRating >= 1.5 &&
          item.feedback.aggregateRating < 2
        "
      >
        <vue-feather
          v-if="item.feedback.aggregateRating >= 1"
          type="star"
        ></vue-feather>
      </div>
      <vue-feather
        v-if="item.feedback.aggregateRating >= 2"
        type="star"
      ></vue-feather>
      <div
        class="w-3 overflow-clip"
        v-if="
          item.feedback.aggregateRating >= 2.5 &&
          item.feedback.aggregateRating < 3
        "
      >
        <vue-feather
          v-if="item.feedback.aggregateRating >= 1"
          type="star"
        ></vue-feather>
      </div>
      <vue-feather
        v-if="item.feedback.aggregateRating >= 3"
        type="star"
      ></vue-feather>
      <div
        class="w-3 overflow-clip"
        v-if="
          item.feedback.aggregateRating >= 3.5 &&
          item.feedback.aggregateRating < 4
        "
      >
        <vue-feather
          v-if="item.feedback.aggregateRating >= 1"
          type="star"
        ></vue-feather>
      </div>
      <vue-feather
        v-if="item.feedback.aggregateRating >= 4"
        type="star"
      ></vue-feather>
      <div
        class="w-3 overflow-clip"
        v-if="item.feedback.aggregateRating >= 4.5"
      >
        <vue-feather
          v-if="item.feedback.aggregateRating >= 1"
          type="star"
        ></vue-feather>
      </div>

      <vue-feather
        v-if="item.feedback.aggregateRating >= 5"
        type="star"
      ></vue-feather>
      <p class="pl-4">{{ getRatingCount }}</p>
    </div>
  </div>
</template>

<script>
export default {
  props: ['item'],
  computed: {
    getRatingCount() {
      return this.item.feedback.reviews.length;
    },
  },
};
</script>
